build: support TensorFlow 2.5 and Python 3.9
zfit/phasespace pull request #40
Opened 2021-05-17 10:26 UTC by redeboer

Hi @mayou36, it seems that `phasespace` can safely update to tensorflow 2.5. (There only seem to be problems with `test_physics.py`, but seems that was already there due to uproot.)

Should anything else be changed?

2021-05-17 10:47 UTC, mayou36 requested changes
That looks good, I would tend to remove 3.6, but we can also leave it another round, no damage done.

2021-05-17 10:47 UTC, mayou36 commented on requirements.txt
> +tensorflow>=2.3
```suggestion
tensorflow>=2.3,<2.6
```
TF is prone to break with version upgrades, so better be safe

2021-05-17 11:42 UTC, mayou36 approved these changes
Looks good, and we can address the test failure in #41

2021-05-17 11:45 UTC, mayou36 commented
I've added you as a maintainer to the repo, so you do have the rights to merge (and more), is that fine? So feel free to merge

2021-05-17 11:48 UTC, redeboer commented
> I've added you as a maintainer to the repo, so you do have the rights to merge (and more), is that fine? So feel free to merge

Thanks! Yeah I'm interested in tackling #39, so that it becomes possible to switch to switch between tensorflow and numpy. I hope to get back to that later this week. Can look into #41 as well then.

2021-05-17 11:48 UTC, merged

2021-05-17 12:07 UTC, mayou36 commented
Okay that sounds good, feel free to assign yourself to issues.

2021-05-26 13:41 UTC, redeboer commented
@mayou36 Could you create a release for this PR? Then tensorwaves can upgrade to TF 2.5 as well ;)
We can also wait until #46 and it's potential follow-up for numpy, but that could be a bit too much for a version bump.

2021-05-26 14:49 UTC, mayou36 commented
Indeed, just making sure that conda forge goes as well